services:
  - type: web
    name: jn-backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: AZURE_SQL_PASSWORD
        sync: false
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,*"