services:
  - type: web
    name: jn-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py migrate --database=django_internal"
    startCommand: "gunicorn jn_custom.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: AZURE_SQL_PASSWORD
        sync: false
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1,*"


